### ISSUE TITLE
Ajouter des explications sur comment répondre quand plusieurs réponses sont possibles

### ISSUE THREAD

**Issue by ichoupinou** [ichoupinou/GL02_MetaDi#15]
**Problème** : difficile à comprendre comment on doit répondre lors de questions à choix multiples. Ajouter une explication avant l'examen ou même un petit tutoriel

**Comment by Speedy-yjo** [comment]
Une explication a été ajoutée avant le début du test, notamment pour les questions à choix multiples. Résoudre cette issue a donné lieu à la création d'une autre issue, qui est de réussir à analyser quand plusieurs réponses sont possibles et que l'utilisateur donne plusieurs réponses.
