### ISSUE TITLE
Vérifier qu'un examen est conforme avant de pouvoir le générer

### ISSUE THREAD

**Issue by Floskobendo** [ichoupinou/GL02_MetaDi#2]
On peut créer un examen en ayant selectionné moins de 15 questions ou plus de 20 questions ce qui n'est pas normal.

Il faut donc empêcher la création de l'examen si il y a moins de 15 questions ou plus de 20 questions.

**Comment by Speedy-yjo** [comment]
La vérification a été rajoutée dans le fichier CreerTestGIFT, et renvoie dans le menu après avoir affiché pourquoi le test ne peut pas être créé
