### ISSUE TITLE
Pouvoir visualiser les réponses d'une question après l'avoir cherchée par mot clé

### ISSUE THREAD

**Issue by Speedy-yjo** [ichoupinou/GL02_MetaDi#5]
**Contexte** : Après avoir fait une recherche, on obtient une liste de questions (plus précisément la liste des consignes des questions et un chiffre y correspondant). 

**Problème** : Mais ensuite on ne peut pas visualiser les réponses possibles à ces questions.

Donc il faut pouvoir visualiser les réponses possibles en donnant le numéro de la question (son numéro d'apparition dans les questions affichées).

**Comment by ichoupinou** [comment]
Ajout de l'affichage des réponses lors d'une recherche
