### ISSUE TITLE
 le GIFT généré n’est pas valide sous format GIFT

### ISSUE THREAD

**Issue by Speedy-yjo** [ichoupinou/GL02_MetaDi#8]
**Problème** : D'après un site de vérification de format GIFT (https://fuhrmanator.github.io/GIFT-grammar-PEG.js/editor/editor.html) le GIFT généré par l'application n'est pas valide. 

Nous avons déjà déterminé qu'il faut rajouter un retour à la ligne entre chaque question pour que le fichier généré soit valide au format GIFT. 

Il faut donc rajouter ce retour à la ligne lors de la génération du fichier GIFT entre chaque question.

**Comment by ichoupinou** [comment]
je remplace dans les string des questions les : car ils interfèrent avec la validité du format GIFT créé
je saute de fois à la ligne entre chaque question pour laisser une ligne vide entre 2 question pour la validité du format GIFT créé
